### ISSUE TITLE
npm install v0.1.2 SyntaxError: Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by yxdh4620** [yuanyan/haste-resolver#1]
/Users/user/test_workspaces/react-web-test/node_modules/haste-resolver-webpack-plugin/node_modules/haste-resolver/lib/index.js:29
    preferNativePlatform: preferNativePlatform, preferNativePlatform: preferNa
                                                ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/user/test_workspaces/react-web-test/node_modules/haste-resolver-webpack-plugin/node_modules/haste-resolver/index.js:16:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by flyskywhy** [comment]
@yxdh4620 , this issue was resolved in latest version
